GAME().world.start_world()

local test_obj = GAME().physics.create_holder_from("PLAYER", 200, 200)
local cam = GAME().camera.create_cam(C_CAMERA_MOVEMENT_TYPE.NORMAL_CURSOR,{target=test_obj.sprite})

GAME().physics.create_holder_from("BLOCK", 200, 250, {width=200,height=50})
GAME().physics.create_holder_from("LIVE_BLOCK", 600, 250, {width=100,height=100})
GAME().physics.create_holder_from("BLOCK", 400, 590, {width=1000,height=20})
GAME().physics.create_holder_from("BLOCK", 300, 450, {width=100,height=25})
GAME().physics.create_holder_from("BLOCK", 500, 400, {width=100,height=25})
GAME().physics.create_holder_from("BLOCK", 700, 450, {width=100,height=100,rot=30})
GAME().physics.create_holder_from("LIVE_BLOCK", 50, 450, {width=100,height=100,update=function(self,dt,body) 
    body:setAngle(self.time)
    self.mesh.rot = math.deg(body:getAngle())
end})

-- GAME().physics.create_holder_from("ENEMY_BAT", 500, 0)
-- GAME().physics.create_holder_from("ENEMY_BAT", 500, 0)
GAME().physics.create_holder_from("ENEMY_BAT", 500, 0)
GAME().physics.create_holder_from("ENEMY_BAT", 500, 0)
GAME().physics.create_holder_from("ENEMY_BARTOX", 500, 0)
GAME().physics.create_holder_from("ENEMY_SPIDER", 500, 0)
